from random import randrange

def choose_icebreaker():
	icebreakers = ['What was your first job?',
		    'Have you ever met anyone famous?',
		    'What are you reading right now?',
		    'If you could pick up a new skill in an instant what would it be?',
		    'Who’s someone you really admire?',
		    'Seen any good movies lately you’d recommend?',
		    'Got any favorite quotes?',
		    'Been pleasantly surprised by anything lately?',
		    'What was your favorite band 10 years ago?',
		    'What’s your earliest memory?',
		    'Been anywhere recently for the first time?',
		    'What’s your favorite family tradition?',
		    'What was the first thing you bought with your own money?',
		    'What’s something you want to do in the next year that you’ve never done before?',
		    'Seen anything lately that made you smile?',
		    'What’s your favorite place you’ve ever visited?',
		    'Have you had your 15 minutes of fame yet?',
		    'What’s the best advice you’ve ever heard?',
		    'How do you like your eggs?',
		    'Do you have a favorite charity you wish more people knew about?',
		    'Got any phobias you’d like to break?',
		    'Have you returned anything you’ve purchased recently? Why?',
		    'Do you collect anything?',
		    'What’s your favorite breakfast cereal?',
		    'What is your most used emoji?',
		    'What was the worst haircut you ever had?',
		    'If you were a wrestler what would be your entrance theme song?',
		    'Have you ever been told you look like someone famous, who was it?',
		    'If you could bring back any fashion trend what would it be?',
		    'What did you name your first car?',
		    'You have your own late night talk show, who do you invite as your first guest?',
		    'What was your least favorite food as a child? Do you still hate it or do you love it now?',
		    'If you had to eat one meal everyday for the rest of your life what would it be?',
		    'If aliens landed on earth tomorrow and offered to take you home with them, would you go?',
		    '60s, 70s, 80s, 90s: Which decade do you love the most?',
		    'What’s your favorite sandwich and why?',
		    'What is your favorite item you’ve bought this year?',
		    'Say you’re independently wealthy and don’t have to work, what would you do with your time?',
		    'If you had to delete all but 3 apps from your smartphone, which ones would you keep?',
		    'What would your dream house be like?',
		    'You’re going sail around the world, what’s the name of your boat?',
		    'Which band / artist – dead or alive would play at your funeral?',
		    'As a child, what did you want to be when you grew up?',
		    'What’s your favorite tradition or holiday?',
		    'What is your favorite breakfast food?',
		    'What is your favorite time of the day and why?',
		    'Coffee or tea?',
		    'Teleportation or flying?',
		    'What is your favorite TV show?',
		    'What book read recently you would recommend and why?',
		    'If you had a time machine, would go back in time or into the future?',
		    'Do you think you could live without your smartphone (or other technology item) for 24 hours?',
		    'What is your favorite dessert?',
		    'What was your favorite game to play as a child?',
		    'Are you a traveler or a homebody?',
		    'What’s your favorite place of all the places you’ve travelled?',
		    'Have you ever completed anything on your “bucket list”?',
		    'What did you have for breakfast this morning?',
		    'What was the country you last visited?',
		    'What is one thing we don’t know about you?',
		    'What is your favorite meal to cook and why?',
		    'Are you a morning person or a night person?',
		    'What is your favorite musical instrument and why?',
		    'What languages do you know how to speak?',
		    'What’s the weirdest food you’ve ever eaten?',
		    'What is your cellphone wallpaper?',
		    'You can have an unlimited supply of one thing for the rest of your life, what is it? ',
		    'What season would you be?',
		    'Are you a good dancer?',
		    'If you could live anywhere in the world for a year, where would it be?',
		    'If you could see one movie again for the first time, what would it be and why?',
		    'If you could rename yourself, what name would you pick?',
		    'If you could have someone follow you around all the time, like a personal assistant, what would you have them do?',
		    'If you had to teach a class on one thing, what would you teach?',
		    'If you could magically become fluent in any language, what would it be?',
		    'If you could eliminate one thing from your daily routine, what would it be and why?',
		    'If you could go to Mars, would you? Why or why not?',
		    'Would you rather live in the ocean or on the moon?',
		    'Would you rather lose all of your money or all of your pictures?',
		    'Would you rather have invisibility or flight?',
		    'Would you rather live where it only snows or the temperature never falls below 40 degrees?',
		    'Would you rather always be slightly late or super early?',
		    'Would you rather give up your smartphone or your computer?',
		    'Would you rather live without AC or live without social media?',
		    'Would you rather be the funniest or smartest person in the room?',
		    'What are your favorite songs from your teenage years that you still rock out to when nobody else is listening?',
		    'What’s your most embarrassing moment from your teen years?',
		    'What’s the worst thing you ever did as a kid — and got away with?',
		    'What did you get into the most trouble for with your parents as a kid?',
		    'What was the first concert you ever went to?',
		    'Do you have any crazy housemate stories?',
		    'What was your first record, tape or CD that you ever owned',
		    'What were words you couldn’t pronounce as a child, so you made up your own?',
		    'Have you ever gotten super lost?',
		    'What was your first job?',
		    'Who was the worst school teacher you ever had?',
		    'What’s the best prank you’ve ever played on someone?',
		    'What’s your strangest talent?',
		    'What show on Netflix did you binge watch embarrassingly fast?',
		    'What is your favorite smell and why?',
		    'What food could you not live without?',
		    'What commercial jingle gets stuck in your head all the time?',
		    'What sport did you try as a child and fail at?',
		    'What do you never leave the house without (can’t be your phone, keys or wallet)?',
		    'What’s a nickname people actually call you?',
		    'If you could only eat at one restaurant forever, what restaurant would it be?',
		    'If you could only wear one type of shoes for the rest of your life, what type of shoes would it be?',
		    'If all your clothes had to be one color forever, what color would you pick?',
		    'If you could eliminate one food so that no one would eat it ever again, what would you pick to destroy?',
		    'If you could turn the ocean into a liquid other than water, which one would you pick?',
		    'If you could only listen to one song for the rest of your life, which song would you pick?',
		    'If you had to endorse a brand, which brand would it be?',
		    'How much does a polar bear weigh?',
		    'Blow our minds with a random fact',
		    'In a zombie apocalypse, what would your survival strategy be?',
		    'Have you ever been skinnydipping?',
		    'What is your best quality?',
		    'You find a high-denomination note in a restaurant floor. Do you hand it in, or pocket it?',
		    'Have you ever had a recurring nightmare?',
		    'What is the kindest thing a stranger has done for you?',
		    'What is your first memory involving a computer?',
		    'What is the weirdest thing you have eaten?',
		    'You can go back in time. Which year do you choose?',
		    'What is one piece of advice you would give to a child?',
		    'Have you ever needed stitches?',
		    'What is your favorite website?',
		    'What was your least favorite subject at school?',
		    'Who is your dream dinner guest?',
		    'Would you rather publish a book or release an album?',
		    'Have you ever met someone famous?',
		    'Have you ever had a supernatural experience?',
		    'Who is your favorite superhero?',
		    'What job would you be doing if computers had not been invented?',
		    'What is the best holiday you have ever been on?',
		    'In the book of your life, what is the best chapter?',
		    'Can you play a musical instrument?',
		    'It is late, you are hungry., What shameful snack will you prepare?',
		    'Make the noise of your favorite animal',
		    'If you could only eat one type of food for the rest of your life, what would it be?',
		    'Day off. What do you do to relax?',
		    'Have you ever been in a newspaper?',
		    'If you could ban any word or phrase, what would it be?',
		    'What was your favorite TV show when growing up?',
		    'Which famous sporting moment would you like to have been part of?',
		    'Do you have superstitions?',
		    'Have you ever walked out of a cinema before a movie has finished?',
		    'What was the one thing you always wanted as a kid, but never got?',
		    'What was the first movie you saw at the cinema?',
		    'You are put in charge of the country. What is the first thing you do?',
		    'What do you like most about coming to work?',
		    'What is your favorite animal?',
		    'What’s the best thing that’s happened to you this week?',
		    'What was the worst present you’ve received?',
		    'Which skill would you love to learn?',
		    'Would you rather be clever or beautiful?',
		    'Would you rather be really hairy or bald?',
		    'Would you like to be taller or shorter?',
		    'What irritates you the most?',
		    'Have you gone out with mismatched socks or shoes on?',
		    'What flavor ice cream you like the most?',
		    'What is your favorite drink?',
		    'Have you ever locked yourself out of the house?',
		    'Have you gone in to a room and forgotten why?',
		    'Given the choice of anyone in the world, whom would you want as a dinner guest?',
		    'Would you like to be famous? In what way?',
		    'Before making a telephone call, do you ever rehearse what you are going to say? Why?',
		    'What would constitute a “perfect” day for you?',
		    'When did you last sing to yourself? To someone else?',
		    'If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?',
		    'Name three things you and a team mate appear to have in common.',
		    'For what in your life do you feel most grateful?',
		    'If you could wake up tomorrow having gained any one quality or ability, what would it be?',
		    'If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?',
		    'Is there something that you’ve dreamed of doing for a long time? Why haven’t you done it?',
		    'What is the greatest accomplishment of your life?',
		    'What do you value most in a friendship?',
		    'What is your most treasured memory?',
		    'What does friendship mean to you?',
		    'Alternate sharing something you consider a positive characteristic of each person in your team.',
		    'Make a true “we” statements. For instance, “We are both in this room feeling ... “',
		    'Share an embarrassing moment in your life.',
		    'What, if anything, is too serious to be joked about?',
		    'Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?',
		    'Texting or talking?',
		    'Favorite day of the week?',
		    'Nickname your parents used to call you?',
		    'Last song you listened to?',
		    'Would you rather be able to speak every language in the world or be able to talk to animals?',
		    'Favorite holiday?',
		    'How long does it take you to get ready?',
		    'Scale of 1-10, how good of a driver are you?',
		    'At what age do you want to retire?',
		    'Invisibility or super strength?',
		    'Is it wrong for a vegetarian to eat animal shaped crackers?',
		    'Scale of 1-10, how good are you at keeping secrets?',
		    'Dawn or dusk?',
		    'Do you snore?',
		    'Place you most want to travel?',
		    'Favorite junk food?',
		    'Favorite season?',
		    'Last Halloween or Carnival costume?',
		    'Cake or pie?',
		    'Do you ever post inspirational quotes on social media?',
		    'Favorite ice cream flavor?',
		    'Say a word in Spanish.',
		    'Favorite number?',
		    'Have you ever worn socks with sandals?',
		    'Try to tickle yourself. Can you?',
		    'What’s the best age?',
		    'If Voldemort offered you a hug, would you accept?',
		    'Would you rather cuddle with a baby panda or a baby penguin?',
		    'Would you want to live forever?',
		    'What will you have for dinner tonight?',
		    'How many pull-ups can you do in a row?',
		    'Favorite type of tea?',
		    'Say something in an Asian language.',
		    'What is the fastest speed you have ever driven in a car?',
		    'Star Trek or Star Wars?',
		    'How many times did you sneeze in the last 7 days?',
		    'Big dogs or small dogs?',
		    'How many hours of sleep do you need?',
		    'Say "Gday mate" in an Australian accent.',
		    'What is your favorite carb: bread, pasta, rice, or potatoes?',
		    'How many kids would you like to have?',
		    'Are rats cute?',
		    'What is your favorite car?',
		    'Do you know how to salsa dance?',
		    'How many cups of coffee do you drink per day?',
		    'What is your ideal outside temperature?',
		    'Favorite type of muffin?',
		    'Giving presents or getting presents?',
		    'From 1-10, how hot do you like your shower water?',
		    'If Kim Kardashian and Donald Trump were both drowning and you could only save one, who would it be?',
		    'Do you like the smell of gasoline?',
		    'Can you touch your toes without bending your knees?',
		    'Have you ever tasted soap?',
		    'Do you currently own any stuffed animals?',
		    'Tapas or pasta?',
		    'Ask permission or ask forgiveness?',
		    'How many redheads are you friends with?',
		    'Name a word in English that starts with the letter Q',
		    'Climb a mountain or jump from a plane?',
		    'If you were really hungry, would you eat a bug?',
		    'How long can you hold your breath for?',
		    'Have you ever seen a kangaroo in person?',
		    'When people stand up for a standing ovation, are you usually one of the earlier people to stand up or one of the later?',
		    'What type of milk do you put in your cereal?',
		    'Did you ever believe in Santa Claus?',
		    'Have you ever been to Africa?',
		    'What is the most number of hours you have watched TV in a single day?',
		    'Do you Instagram your food?',
		    'What sound does a seal make?',
		    'Would you rather lose all your hair or gain 50% more hair?',
		    'If there is a spider in your house, do you kill it or set it free?',
		    'What is something you could eat for a week straight?',
		    'Would you rather wake up to an air horn blowing in your ear every day, or wake up and have to run 4 miles every day?',
		    'Dark Chocolate or Milk Chocolate?',
		    'Would you go to a cinema alone?',
		    'What is a country you would be okay never visiting in your life?',
		    'Would you rather eat some smoky gnocchi or some delish fish?',
		    'If you were given the opportunity to fly into space given current technology, would you take it?',
		    'When was the last time you stayed up past 4 in the morning?',
		    'When you fly on a plane, do you wear a neck pillow?',
		    'Do you like Disneyland?',
		    'How would you rate your karaoke skills on a scale of 1 to Mariah Carey?',
		    'Are tomatoes a fruit or a vegetable?',
		    'Have you ever stolen anything?',
		    'Do you think anyone considers you a hipster?',
		    'What’s the sound you would make if you were freezing cold?',
		    'What’s your favorite martial art?',
		    'Los Angeles or New York?',
		    'Super Mario Brothers or Zelda?',
		    'What temperature do you like your thermostat at?',
		    'Do you own a bicycle?',
		    'Do you find moustaches to be handsome?',
		    'Which animal adds more joy to the world, squirrels or llamas?',
		    'On a scale of 1-10 how much do you enjoy garlic?',
		    'Who inspires you?',
		    'If there was a hair in your soup at a restaurant, would you return it?',
		    'What is the most boring thing ever?',
		    'What bed size do you prefer?',
		    'What’s your middle name?',
		    'What’s your current state of mind?',
		    'What’s one thing that most people don’t know about you?',
		    'What would other people say you’re exceptionally good at? Why?',
		    'Name 3 things that you and your team have in common.',
		    'What is one thing in your life that feels stressful right now?',
		    'What’s one embarrassing thing that’s happened to you since working here?',
		    'When was the last time you asked a teammate for help? What happened?',
		    'What’s one thing you’ve learned from your team? What does it mean to you?',
		    'How might we learn from each other more often?',
		    'What professional skills would you like to develop next?',
		    'Who in the company would you like to learn from? What would you like to learn?',
		    'Where do you imagine yourself 5 years from now?',
		    'Think about yourself one year ago. What’s one thing that’s changed since then?',
		    'What’s working particularly well on your team right now?',
		    'What are some things we could do to celebrate success more often?',
		    'How would teammates describe your communication style?',
		    'How do you feel about small talk?',
		    'What’s one time where a team took a risk, and it paid off?',
		    'When in your career have you felt the most purpose in your work?',
		    'What’s your favorite charitable or non-profit organization? Why?',
		    'What does leadership mean to you?',
		    'Who inspired you this week? Why?',
		    'How do you recognize when you’re stressed?',
		    'What’s one thing you you’ve learned from reading lately?',
		    'What book would benefit your team if you read it together?',
		    'How would you describe how work felt this month, using only phrases from a weather forecast?',
		    'How do you tend to see the world? Always sunny? Always stormy? Something else?',
		    'Who has helped make your job easier recently? What did they do?',
		    'What fun topic could you give a short presentation about with no preparation?',
		    'How do you feel about public speaking? Love it? Hate it? Both?',
		    'Where, outside of work, do you get your best ideas?',
		    'Have you ever had a helpful deadline? What made it helpful?',
		    'Do you have any routines you use to improve your energy and focus?',
		    'What’s one thing you’ve learned in the past month?',
		    'Who is a good listener on your team? What makes them good at it?',
		    'When does it feel easy for you to be a good listener?',
		    'What would you rather hear first, good news or bad news?',
		    'How do you get feedback on your own work? What questions do you ask?',
		    'What’s a piece of useful feedback you’ve received from a teammate?',
		    'Think of a time when feedback felt like a gift. Why did it feel that way?',
		    'When you give feedback, how do you make sure it’s received as helpful?',
		    'Who was your favorite teacher? What made them special?',
		    'What’s a part of your job that you particularly enjoy?',
		    'Who has made a positive difference in your life recently?',
		    'What’s the funniest thing that’s ever happened to you while working here?',
		    'What did you get into the most trouble for as a kid?',
		    'What’s a healthy fear that drives you and makes you more effective?',
		    'When looking back at your youth, what was your silliest fear?',
		    'What’s your meeting load like recently? Too many? Too few? Just right?',
		    'What meeting do you benefit the most from attending?',
		    'If you had an extra day to focus uninterrupted on any project, what would you work on?',
		    'How should teammates know when it’s a bad time to interrupt you?',
		    'Who has been an influential mentor to you?',
		    'What’s a mobile app that you love, but that few people know about?',
		    'Do you find it easier to say yes to projects, or no to projects? Why’s that?',
		    'When you need to say “no” to a project, what are some techniques you use?',
		    'What’s one thing you don’t like doing, but manage to do anyway?',
		    'When you find that part of a project is unpleasant, how do you manage to keep going?',
		    'If you could complete one work-related task with a wave of your hand, what task would you choose?',
		    'What’s one TV show you think your whole team should watch? Why?',
		    'What part of your job are you most passionate about?',
		    'What’s one thing you’re grateful for at work?',
		    'What character trait are you thankful that you possess?',
		    'When times are tough, who or what reminds you that life is good?',
		    'What’s one strange thing you used to believe as a child?',
		    'What’s one rule your parents or guardians enforced when you were a kid?',
		    'How do you mentally step away from work at the end of the day?',
		    'When do you find it hardest to stop thinking about work?',
		    'Do you tend to think out loud, or wait till you know just what to say?',
		    'How would you rather start a meeting: Get to business, or get to know each other?',
		    'What does “communication style” mean to you?',
		    'Do you tend to stay calm and cool, or get easily excited?',
		    'How long does it take you to warm up to a new group of people?',
		    'What’s one internet meme or cultural phenomenon that baffles you?',
		    'What would be helpful for your teammates to know about the way you communicate?',
		    'Has there been a day when your daily routine was thrown off recently? How did you adapt?',
		    'Is there any part of your daily routine that you’d like to change? Why?',
		    'What have you read or watched recently and enjoyed?',
		    'For those that might not know, what’s your role here?',
		    'What were you doing before working here?',
		    'What do you like to do for fun?',
		    'What are some hobbies or activities you do outside of work?',
		    'What’s your morning routine like?',
		    'If you could travel anywhere in the world, where would you go? Why?',
		    'Who are your heroes in real life?',
		    'What was your favorite cartoon as a kid?',
		    'Which comedian, actor, or author really makes you laugh?',
		    'What is your favorite holiday? Why?',
		    'What was the best thing that happened to you in the last week?',
		    'If you could invent a new flavor of ice cream, what would it be?',
		    'What’s the last dream that you remember?',
		    'What’s one strange thing that’s happened to you since working here?',
		    'What’s the worst haircut you’ve ever had?',
		    'How did you find your way to your current career? What was your journey?',
		    'If you had to sum up your entire career in 12 words or less, what would you say?',
		    'Do you like to get up early, or stay up late? Has this ever been challenging?',
		    'What’s one fun thing you’ve learned outside of work recently?',
		    'When you were younger, what did you want to be when you grew up?',
		    'What’s one skill that you’ve improved in the last year? How did you do it?',
		    'If you took a 4-week paid sabbatical from work, what would you do with the time?',
		    'Who do you admire? What do you admire about them?',
		    'If you had to move to a different country, where would you go? What would you miss?',
		    'If this team had a mascot, what would it be?',
		    'What conversations are you most looking forward to this week?',
		    'What’s your favorite meeting at work? Why?',
		    'If you could get a meeting with anyone in the world, who would it be? Why?',
		    'What’s one moment of success you experienced recently?',
		    'What recent team accomplishment brings you the most joy? Why?',
		    'How do you celebrate? What are some things you do to treat yourself?',
		    'What’s your email style? Brief or detailed? Emotive or serious?',
		    'Do you consider yourself an introvert, an extrovert or both? Why?',
		    'What’s your superpower? How do you use it at work?',
		    'Imagine an ideal day at work. How do you spend it? What happens?',
		    'What’s one thrilling thing you’ve done?',
		    'What’s the most beautiful place you’ve ever been?',
		    'What’s your favorite way to relax or unplug?',
		    'What excited you most when joining this team?',
		    'What is the best team experience of your career? What made it so great?',
		    'Back at school, were you on any teams or in any clubs? What was your favorite? Why?',
		    'What was the last thing someone thanked you for?',
		    'What is your favorite walk, hike, or bike ride?',
		    'What song or artist have you been listening to lately?',
		    'What books are on the top of your “want to read” list?',
		    'What’s your favorite children’s book? Why?',
		    'What’s your favorite season? Why?',
		    'What seemingly tiny thing are you especially grateful for?',
		    'If you could make a guest appearance in a TV show, which show would it be?',
		    'What TV or movie character would be amazing on your team? Why?',
		    'What talk or presentation have you enjoyed watching recently?',
		    'What languages do you speak? How did you learn to speak them?',
		    'When was the last time you were so into your work that time flew by?',
		    'Outside of work, what activity makes you lose track of time?',
		    'When you set a morning alarm, do you snooze for a while, or wake up right away?',
		    'When during the day do you have the most energy and focus?',
		    'What’s the perfect notebook for you? (Lines or grids? Big or small? Etc.)',
		    'What’s a favorite item that you’ve had on your desk at some point?',
		    'If you had an extra day a week to volunteer your time, what would you do?',
		    'What business jargon would you like to banish from the workplace?',
		    'What was the last podcast or audiobook you listened to?',
		    'If you could magically improve at one skill, what would it be?',
		    'What categories of trivia are you the best at?',
		    'What should be M&amp;M’s next new color or flavor?',
		    'What’s one thing you enjoy about your home or neighborhood?',
		    'What’s a simple pleasure you enjoyed this week?',
		    'What’s your favorite story to tell about company history?',
		    'What work decision or policy would you most like to know the backstory for?',
		    'If you could add any snack to the kitchen at work, what would it be?',
		    'What helps you wake up: coffee, tea, or something else?',
		    'What food do you hate the most?',
		    'What was the last scary movie that you’ve seen?',
		    'What musical instruments have you played, either now or in the past?',
		    'If you could have any car for free, what would you drive? (Assuming free parking, gas, etc.)',
		    'In your kitchen, what’s your favorite tool or gadget?',
		    'What’s your favorite sport to play or watch?',
		    'Where’s your favorite place for lunch on a workday?',
		    'What’s your favorite Olympic event to watch? What do you like about it?',
		    'What fictional character would you most like to have as a mentor?',
		    'What’s the furthest away from home you’ve ever been?',
		    'Where would you like to go on your next vacation?',
		    'When you read books for fun, do you feel the need to finish them completely? Why?',
		    'What’s your least favorite chore?',
		    'What small activities help you re-energize?',
		    'You’ve been tasked with creating a real superhero. What would their superpower be?',
		    'What was your favorite television series as a teenager?',
		    'What movie will you never grow tired of watching?',
		    'What’s a movie that should have had a sequel, or a sequel that shouldn’t have been made?',
		    'What are two things you’re passionate about outside of work?',
		    'What’s one great thing that happened to you this week?',
		    'How do you approach traveling on vacation? Do you make an itinerary or just explore?',
		    'Have you ever dealt with a series of unfortunate events on a vacation? How did you overcome it?',
		    'If you could spend a season working abroad, where would you go?',
		    'Kids today will never understand the struggle of what?',
		    'When do you find it easiest to stop thinking about work?',
		    'How do you power down at the end of the week to make sure you enjoy your weekend?',
		    'How do you like to work: deep focused time, or quickly switching contexts?',
		    'What’s the perfect temperature setting for the office thermostat?',
		    'What’s your favorite figure of speech?',
		    'Which do you prefer: hot weather or cold weather? Why is that?',
		    'When looking for something at the store, do you ask someone or try to find it yourself?',
		    'What’s your favorite food these days? How often do you get to enjoy it?',
		    'How does your daily routine change from weekday to weekend?',
		    'What is the best piece of advice you’ve received? Why was it helpful?',
		    'What’s one thing that could work better on your team?',
		    'What’s one pet peeve you have about the way other people communicate with you?',
		    'What are a few ways in which you express your gratitude?',
		    'Think about the last mistake you made at work. What happened? What did you learn?',
		    'What would you do at work if you knew you couldn’t fail?',
		    'Think of the biggest professional risk you’ve taken. What helped you take that risk?',
		    'What would make you feel safer when taking calculated risks at work?',
		    'What things make it harder or easier for a group to feel like a team?',
		    'How could we make this team feel like more like a team?',
		    'What kind of leader do you want to be? What’s your personal leadership style?',
		    'When you’re feeling stressed, how do you deal with it?',
		    'Describe a real-life situation where you stood up for someone or something.',
		    'When people have different opinions on the team, what happens?',
		    'What was the last team decision that felt like it took too long? Why did it take so long?',
		    'How does your outlook on the world affect your approach to work?',
		    'Think of the last meaningful “thank you” that you received. What was it?',
		    'How do you like be thanked at work? In public or private?',
		    'What distractions prevent you from doing your best work?',
		    'What’s one deadline that you almost missed?',
		    'When do deadlines create more problems than they solve?',
		    'Are there any productivity habits that you wish you could get into?',
		    'When is it difficult for you to listen to others?',
		    'If you could give your younger self a piece of advice, what would you say?',
		    'Think of a time when feedback was NOT helpful to you. What went wrong?',
		    'What’s a fear that sometimes gets in your way?',
		    'If you had to skip one recurring meeting, which meeting would you skip? Why?',
		    'What could you change to give yourself more uninterrupted time to focus?',
		    'How has mentorship affected you throughout your career?',
		    'Is there any topic lately that you would like to be mentored on?',
		    'What’s one project that you could stop doing to give yourself more focus?',
		    'What’s the hardest thing you’ve ever done? How did you make it through?',
		    'How do you overcome frustration at work?',
		    'Imagine you’ve just had a difficult interaction with a colleague. How do you regain focus?',
		    'What is a passion of yours you’ve yet to act on?',
		    'What 3 words would you use to describe yourself to a stranger?',
		    'Which of your character traits do you think adds the most value to the world?',
		    'What’s something about you that would surprise most people who know you?',
		    'What’s a trip that changed you? How were you changed?',
		    'Looking back, what do you admire most about your childhood self?',
		    'When there’s disagreement, do you tend to lean into it, or away from it?',
		    'When was the last time you had a small misunderstanding? What happened?',
		    'What’s one misunderstanding that’s happened on your team recently? How was it resolved?',
		    'Imagine that communication totally breaks down between you and someone else. How is it likely to happen?',
		    'How would you describe your communication style in 3 words?',
		    'How does your particular communication style affect the people around you?',
		    'Are there times when you find it difficult to ask for help with your own work?',
		    'What’s a time when you should have asked for help sooner but waited? Is there anything that might have made it easier for you to ask?',
		    'Where does career growth rank in your list of priorities?',
		    'What gives you peace of mind?',
		    'Has social media made the world a better place?',
		    "What's the best meal you've ever had?",
		    'What impact has family had on your idea of success?',
		    'How has your taste in music changed over time?',
		    "What's more important: the individual or the collective good?",
		    'Are you artistic?',
		    'Share a positive characteristic of each person in this group',
		    'Are there any funny stories your family tells about you that come to mind?',
		    "What's one new and interesting thing you've been thinking about lately?",
		    "What's one thing that brings you energy and joy?",
		    'What kind of day have you had so far today?',
		    'Name a weather status that matches your mood',
		    'If you could invite someone to sit next to you today, who would it be?',
		    'Describe where your head and your heart are right now',
		    'What important skill do you believe everyone should have?',
		    'Which technological innovation made the most impact on your life?',
		    'How would you spend one million dollars? And five million?',
		    'Imagine you had a tattoo. What would it be and where would you have it?',
		    'Which dish would you like to learn to cook next?',
		    'What Disney character are you?',
		    'What event in the past or future would you like to witness in person?',
		    'What kind of party would you throw if you had unlimited budget?',
		    'Who would you like to trade places with for a month?',
		    'What are the best and worst things about being an adult?',
		    'What new name would you choose for yourself?',
		    'What’s the most embarrassing fashion trend you used to rock?',
		    'What would the title of your autobiography be?',
		    'What does your favorite shirt look like?',
		    'What fictional family would you be a member of?',
		    'What sport would you compete in if you were in the Olympics?',
		    'Do you have a favorite plant?',
		    'What fictional world or place would you like to visit?',
		    'Popcorn or M&Ms?',
		    'Would you rather be an Olympic gold medallist or an astronaut?',
		    'What are your favorite pizza topings?',
		    'Do you have any Christmas traditions?',
		    'Do you have any siblings?',
		    'Have you ever broken a bone?',
		    'Did you make your bed this morning?',
		    'Where did you grow up?',
		    'Do you know any good jokes? (Dad jokes are allowed)',
		    'What is the farthest distance you have driven?',
		    'How many pairs of shoes do you own?',
		    'How many books did you read last year?',
		    'Do you have any pets?',
		    'Where were you born?',
		    'Wine or Beer?',
		    'What would you add to your coffee: Baileys, Amaretto, Whisky or Milk?',
		    'What do you enjoy most about the holidays?',
		    'What is the best concert you have ever been to?',
		    'If you created a photo calendar, what photo would you put on November?',
		    'What board game are you unbeatable at?',
		    'Do you have any short term goals?',
		    'Favorite Christmas movie?',
		    'What is your favourite fast food restaurant?',
		    'Which is typically better, the book or the movie?',
		    'What is your favourite app?',
		    'Who is your least favourite actor?',
		    'When and how did you learn the truth about Santa?',
		    'Favourite snack to eat while watching a movie?',
		    'Is a hotdog a sandwich?',
		    'What food can you not stand?',
		    'Dancing in the rain or saying cozy inside?',
		    'Luxury beach vacations or backpacking?',
		    'What was the best team building you ever participated?',
		    "What is something you do that you don't like to do?",
		    'Imagine you were given a kitten, what would you name her/him?',
		    'If you could add anything to your desk, what would it be?',
		    'If you could collect anything, what would it be?',
		    'What is your favourite scent?',
		    'Do you enjoy rollercoasters?',
		    'Do you have a favourite childhood videogame?',
		    'What is your cocktail of choice?',
		    'What is something that frustrates you at work?',
		    'Do you have a guilty pleasure?',
		    'Are you a clean or a messy person?',
		    'Conflicts: avoid or confront?',
		    'What is your favourite photograph?',
		    'Do you have any tattoos?',
		    'Best way to get over a breakup?',
		    'Use one word to describe your childhood bedroom',
		    'Do you have any hidden talents?',
		    'Is there any habit you would like to change?',
		    "Tell us one of the most important lessons you've learned in life",
		    "Is there something about your team members that you've always wanted to ask but never did?",
		    'Favourite memory of your team?',
		    'What is your most valuable travel advice?',
		    'Of all your possessions, what would be the hardest to give up?']
	return icebreakers[randrange(0, len(icebreakers) - 1, 1)]